### ISSUE TITLE
希望增加对安卓12的支持

### ISSUE THREAD

**Issue by Dream940** [tsukiseele/MoeViewerR#3]
如题。很多图库失效了

**Comment by Dream940** [comment]
图库省略图不显示。以及个别图库无法读取。

**Comment by tsukiseele** [comment]
该项目正在使用Flutter重写以支持更多平台，这些问题将逐步得到解决，请参见[ComicNyaa](https://github.com/tsukiseele/ComicNyaa).
感谢您提交的问题
